### ISSUE TITLE
你好，我新建了mpvue项目，按照文档走，但是还是报错，望查看

### ISSUE THREAD

**Issue by yuziyuan** [Rychou/mpvue-vant#44]
文档：https://segmentfault.com/a/1190000016228410?utm_source=tag-newest
环境： mpvue
mpvue文档： http://mpvue.com/mpvue/#_2

报错代码：

VM441:1 thirdScriptError 
 sdk uncaught third Error 
 Unexpected token import 
 SyntaxError: Unexpected token import
console.error @ VM441:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
e @ appservice?t=1550301892491:4652
window.onerror @ VM441:1
app.js:101 app created and cache logs by setStorageSync
VM441:1 thirdScriptError 
 sdk uncaught third Error 
 module "static/vant/action-sheet/index.js" is not defined 
 Error: module "static/vant/action-sheet/index.js" is not defined
    at require (http://127.0.0.1:51932/appservice/__dev__/WAService.js:1:912710)
    at <anonymous>:155:7
    at HTMLScriptElement.scriptLoaded (http://127.0.0.1:51932/appservice/appservice?t=1550301892491:5318:21)
    at HTMLScriptElement.script.onload (http://127.0.0.1:51932/appservice/appservice?t=1550301892491:5330:20)
console.error @ VM441:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
e @ appservice?t=1550301892491:4652
window.onerror @ VM441:1
scriptLoaded @ appservice?t=1550301892491:5318
script.onload @ appservice?t=1550301892491:5330
VM441:1 jsEnginScriptError
Component is not found in path "static/vant/button/index" (using by "pages/inteSearchRoom/main");onAppRoute
Error: Component is not found in path "static/vant/button/index" (using by "pages/inteSearchRoom/main")
    at e (http://127.0.0.1:51932/appservice/__dev__/WAService.js:1:784898)
    at e (http://127.0.0.1:51932/appservice/__dev__/WAService.js:1:785084)
    at http://127.0.0.1:51932/appservice/__dev__/WAService.js:1:800443
    at Object.t.addView (http://127.0.0.1:51932/appservice/__dev__/WAService.js:1:800989)
    at Function.value (http://127.0.0.1:51932/appservice/__dev__/WAService.js:1:879601)
    at Ct (http://127.0.0.1:51932/appservice/__dev__/WAService.js:1:895341)
    at xt (http://127.0.0.1:51932/appservice/__dev__/WAService.js:1:897187)
    at It (http://127.0.0.1:51932/appservice/__dev__/WAService.js:1:898500)
    at Function.<anonymous> (http://127.0.0.1:51932/appservice/__dev__/WAService.js:1:899368)
    at Nt.<anonymous> (http://127.0.0.1:51932/appservice/__dev__/WAService.js:1:873037)

**Comment by Rychou** [comment]
```
module "static/vant/action-sheet/index.js" is not defined
Error: module "static/vant/action-sheet/index.js" is not defined
```

您好 看报错信息，应该是组件模块没找到。请问开发者工具的`ES6转ES5`开了吗？其次检查一下`dist/wx/static/vant`目录下是否有对应组件文件
